/**
 * Declares every block available to terrain generation, rendering, collision, and the hotbar.
 * Systems consume this shared metadata instead of maintaining conflicting block-specific rules.
 */

/** Numeric block identifiers are stored directly in compact chunk byte arrays. */
export enum BlockId {
  Air = 0,
  Grass = 1,
  Dirt = 2,
  Stone = 3,
  Sand = 4,
  Wood = 5,
  Leaves = 6,
  Cobblestone = 7,
}

/** Texture names correspond to cells generated by the procedural atlas. */
export type TextureName =
  | "grass-top"
  | "grass-side"
  | "dirt"
  | "stone"
  | "sand"
  | "wood-side"
  | "wood-top"
  | "leaves"
  | "cobblestone";

/** Face categories let vertical blocks choose distinct cap and side textures. */
export type BlockFace = "top" | "bottom" | "side";

/** Shared metadata defines how a block behaves and appears throughout the game. */
export interface BlockDefinition {
  readonly id: BlockId;
  readonly name: string;
  readonly solid: boolean;
  readonly occludesFaces: boolean;
  readonly textures: Readonly<Record<BlockFace, TextureName>>;
  readonly uiColor: string;
}

// All solid blocks currently occlude neighboring faces because the initial release uses opaque materials.
export const BLOCK_DEFINITIONS: Readonly<Record<BlockId, BlockDefinition>> = {
  [BlockId.Air]: {
    id: BlockId.Air,
    name: "Air",
    solid: false,
    occludesFaces: false,
    textures: { top: "dirt", bottom: "dirt", side: "dirt" },
    uiColor: "#000000",
  },
  [BlockId.Grass]: {
    id: BlockId.Grass,
    name: "Grass",
    solid: true,
    occludesFaces: true,
    textures: { top: "grass-top", bottom: "dirt", side: "grass-side" },
    uiColor: "#6fa640",
  },
  [BlockId.Dirt]: {
    id: BlockId.Dirt,
    name: "Dirt",
    solid: true,
    occludesFaces: true,
    textures: { top: "dirt", bottom: "dirt", side: "dirt" },
    uiColor: "#8b5a35",
  },
  [BlockId.Stone]: {
    id: BlockId.Stone,
    name: "Stone",
    solid: true,
    occludesFaces: true,
    textures: { top: "stone", bottom: "stone", side: "stone" },
    uiColor: "#888888",
  },
  [BlockId.Sand]: {
    id: BlockId.Sand,
    name: "Sand",
    solid: true,
    occludesFaces: true,
    textures: { top: "sand", bottom: "sand", side: "sand" },
    uiColor: "#d9c27a",
  },
  [BlockId.Wood]: {
    id: BlockId.Wood,
    name: "Wood",
    solid: true,
    occludesFaces: true,
    textures: { top: "wood-top", bottom: "wood-top", side: "wood-side" },
    uiColor: "#8a6238",
  },
  [BlockId.Leaves]: {
    id: BlockId.Leaves,
    name: "Leaves",
    solid: true,
    occludesFaces: true,
    textures: { top: "leaves", bottom: "leaves", side: "leaves" },
    uiColor: "#477f3a",
  },
  [BlockId.Cobblestone]: {
    id: BlockId.Cobblestone,
    name: "Cobblestone",
    solid: true,
    occludesFaces: true,
    textures: { top: "cobblestone", bottom: "cobblestone", side: "cobblestone" },
    uiColor: "#6f7374",
  },
};

// Hotbar order is stable so number keys always select the same material.
export const HOTBAR_BLOCKS: readonly BlockId[] = [
  BlockId.Grass,
  BlockId.Dirt,
  BlockId.Stone,
  BlockId.Sand,
  BlockId.Wood,
  BlockId.Leaves,
  BlockId.Cobblestone,
];

/** Returns validated metadata for a block identifier; unknown save data becomes air safely. */
export function getBlockDefinition(blockId: BlockId): BlockDefinition {
  return BLOCK_DEFINITIONS[blockId] ?? BLOCK_DEFINITIONS[BlockId.Air];
}

/** Reports whether the player must collide with the requested block. */
export function isSolidBlock(blockId: BlockId): boolean {
  return getBlockDefinition(blockId).solid;
}

/** Reports whether a neighboring cube can hide a face during mesh construction. */
export function blockOccludesFaces(blockId: BlockId): boolean {
  return getBlockDefinition(blockId).occludesFaces;
}

/** Selects the appropriate atlas texture for a horizontal, upper, or lower cube face. */
export function getBlockTexture(blockId: BlockId, face: BlockFace): TextureName {
  return getBlockDefinition(blockId).textures[face];
}

/** Validates untrusted persisted numbers before they enter typed world storage. */
export function isBlockId(value: unknown): value is BlockId {
  return (
    typeof value === "number" &&
    Number.isInteger(value) &&
    value >= BlockId.Air &&
    value <= BlockId.Cobblestone
  );
}
